/*
 * This Java source file was auto generated by running 'gradle buildSetup --type java-library'
 * by 'twer' at '8/25/13 7:24 AM' with Gradle 1.7
 *
 * @author twer, @date 8/25/13 7:24 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
